import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
    mode: deep_merge_prepend
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml
language: python
python: '3.5'
install:
 - pip install pylint
script:
 - PYTHONPATH=test-packages python3 -m pylint qubeswhonix
